name: Deploy Laravel to SiteGround

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to SiteGround
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SGSSH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 18765 ssh.givingtalents.org >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Sync Laravel core (excluding /public) to laravel/
        run: |
          echo "Testing SSH connection..."
          ssh -vvv -p 18765 -i ~/.ssh/id_rsa u1083-2m4vcwbgzr7k@ssh.givingtalents.org "echo 'SSH connected OK'"

          echo "Starting rsync..."
          rsync -avz --delete \
            --exclude .git --exclude .env --exclude node_modules --exclude vendor \
            -e "ssh -p 18765 -o StrictHostKeyChecking=no" \
            ./ u1083-2m4vcwbgzr7k@ssh.givingtalents.org:~/www/givingtalents.org/laravel/

      - name: Run Composer Install via SSH
        run: |
          ssh -p 18765 -o StrictHostKeyChecking=no u1083-2m4vcwbgzr7k@ssh.givingtalents.org << 'EOF'
            cd /home/customer/www/givingtalents.org/laravel
            composer install --no-dev --optimize-autoloader
          EOF

      - name: Confirm Deployment Finished
        run: echo "✅ Deployment complete!"
